// generated by mBlock5 for <your product>
// codes make you happy

#include <Servo.h>
#include <Arduino.h>
#include <Wire.h>
#include <SoftwareSerial.h>
#include "Stepper.h"

float x_endstop_value = 0;
float y_endstop_value = 0;
float home = 0;
float xmax = 0;
float ymax = 0;
float ciblex = 0;
float cibley = 0;
float pos_x = 0;
float pos_y = 0;

Servo servo_22;
Stepper stepper_1(2048,30,32,34,36);

Stepper stepper_2(2048,40,42,44,46);

void _delay(float seconds) {
  long endTime = millis() + seconds * 1000;
  while(millis() < endTime) _loop();
}

void setup() {
  pinMode(2,OUTPUT);
  pinMode(3,OUTPUT);
  pinMode(4,OUTPUT);
  servo_22.attach(22);
  stepper_1.setSpeed(10);
  stepper_2.setSpeed(10);
  pinMode(11,OUTPUT);
  pinMode(50,INPUT);
  pinMode(51,INPUT);
  voidrgb_y() {
    analogWrite(2,255);
    analogWrite(3,120);
    analogWrite(4,0);
    }
  voidpenup1() {
    servo_22.write(80);
    _delay(1);
    }
  voidpenup0() {
    servo_22.write(120);
    _delay(1);
    }
  voidgoto_() {
    rgb_y();
    if(pos_x < ciblex){
      while(!(pos_x == ciblex)){
        stepper_1.step(-10);
        pos_x += 10;

      }

    }
    if(pos_x > ciblex){
      while(!(pos_x == ciblex)){
        stepper_1.step(10);
        pos_x += -10;

      }

    }
    if(pos_x == ciblex){

    }
    if(pos_y < cibley){
      while(!(pos_y == cibley)){
        stepper_2.step(10);
        pos_y += 10;

      }

    }
    if(pos_y > cibley){
      while(!(pos_y == cibley)){
        stepper_2.step(-10);
        pos_y += -10;

      }

    }
    if(pos_y == ciblex){

    }
    }
  penup0();
  xmax = 1430;
  ymax = 1095;
  y_endstop_value = -10;
  x_endstop_value = 10;
  home = 0;
  tone(11,1760,0.1*1000);
  delay(0.1*1000);
  stepper_1.step(-120);
  stepper_2.step(120);
  _delay(1);
  while(!(digitalRead(50) == 0.000000)){
    stepper_1.step(x_endstop_value);

  }
  home += 0.5;
  _delay(1);
  while(!(digitalRead(51) == 0.000000)){
    stepper_2.step(y_endstop_value);

  }
  home += 0.5;
  if(home < 1.1){
    pos_x = 0;
    pos_y = 0;
    tone(11,1976,0.25*1000);
    delay(0.25*1000);

  }
  _delay(1);

}

void _loop() {
}

void loop() {
  _loop();
}

